"""Render ``model_card.md`` — metadata model untuk dokumentasi (PRD §B.1)."""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def render_model_card(
    out_path: str | os.PathLike[str],
    *,
    model_name: str = "ResNet50-U-Net (ForestWatch Papua)",
    architecture: str = "U-Net",
    encoder: str = "ResNet-50 (ImageNet pretrained)",
    in_channels: int = 6,
    n_classes: int = 6,
    patch_size: int = 256,
    n_parameters: int | None = None,
    training_dataset: str = "Sentinel-2 SR Harmonized + ESA WorldCover + Dynamic World + Hansen GFC + BIOPAMA Oil Palm",
    training_period: str = "Citra: 2025 (untuk training); pembanding: 2021",
    area: str = "Papua, Indonesia (6 provinsi, bbox 130°–141,2°E, -9,5°–0,5°N)",
    metrics: dict[str, Any] | None = None,
    epochs: int | None = None,
    batch_size: int | None = None,
    optimizer: str = "AdamW (lr=1e-3, weight_decay=1e-4)",
    loss: str = "0.6 × CrossEntropy(weighted) + 0.4 × Dice",
    limitations: list[str] | None = None,
    intended_use: list[str] | None = None,
    citation: str | None = None,
    extra_sections: dict[str, str] | None = None,
) -> Path:
    """Tulis ``model_card.md`` siap-baca (markdown) dengan section standar.

    Mengikuti gaya Hugging Face Model Card + PRD context.
    """
    if metrics is None:
        metrics = {}
    if limitations is None:
        limitations = [
            "Sentinel-2 adalah sensor optik — tutupan awan tinggi di Papua mengurangi data per pixel.",
            "Hansen GFC bersumber Landsat 30 m yang di-resample ke 10 m; morphological erosion 1 piksel digunakan untuk mengurangi noise tepi.",
            "BIOPAMA Oil Palm v1 hanya tahun 2019 — sawit muda pasca-2019 ditangkap via deteksi perubahan, bukan kelas statis.",
            "Sawit muda (0–3 tahun) sulit dibedakan dari semak karena kanopi belum menutup.",
            "Kelas Tambang berasal dari Global Mining Footprint (Tang & Werner 2023, snapshot ~2023); ekspansi tambang terbaru perlu pemutakhiran dataset.",
        ]
    if intended_use is None:
        intended_use = [
            "Penelitian, kompetisi (SEC SATRIA DATA 2026), dan eksplorasi tata kelola data kehutanan.",
            "Pilot/prototype WebGIS untuk visualisasi publik.",
            "BUKAN untuk keputusan hukum / kebijakan operasional tanpa validasi lapangan (ground truthing).",
        ]
    if citation is None:
        citation = (
            "ForestWatch Papua Team (Universitas Andalas). 2026. "
            "ForestWatch Papua — Sistem Deteksi Dini Deforestasi Berbasis Deep Learning "
            "dari Citra Satelit Sentinel-2. SEC SATRIA DATA 2026."
        )

    overall = metrics.get("overall_accuracy", "—")
    miou = metrics.get("mean_iou", "—")
    per_class = metrics.get("per_class", [])

    per_class_lines = "\n".join(
        f"| {row.get('class', '?')} | {row.get('iou', '—'):.4f} | {row.get('f1', '—'):.4f} |"
        if isinstance(row.get("iou"), (int, float))
        else f"| {row.get('class', '?')} | {row.get('iou', '—')} | {row.get('f1', '—')} |"
        for row in per_class
    ) or "| (belum tersedia) | — | — |"

    limitations_md = "\n".join(f"- {item}" for item in limitations)
    intended_use_md = "\n".join(f"- {item}" for item in intended_use)

    extra_md = ""
    if extra_sections:
        for title, body in extra_sections.items():
            extra_md += f"\n\n## {title}\n\n{body}"

    md = f"""# Model Card — {model_name}

*Generated: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}*

## Ringkasan

- **Arsitektur**: {architecture}
- **Encoder**: {encoder}
- **Input**: {in_channels} band Sentinel-2, patch {patch_size}×{patch_size}
- **Output**: {n_classes} kelas tutupan lahan (segmentasi semantik)
{"- **Parameter**: " + f"{n_parameters:,}" if n_parameters else ""}

## Data Latih

- **Sumber citra**: {training_dataset}
- **Periode**: {training_period}
- **Wilayah**: {area}

## Training

- **Optimizer**: {optimizer}
- **Loss**: {loss}
{"- **Epochs**: " + str(epochs) if epochs else ""}
{"- **Batch size**: " + str(batch_size) if batch_size else ""}

## Hasil Evaluasi

- **Overall Accuracy**: {overall}
- **Mean IoU**: {miou}

| Kelas | IoU | F1 |
| --- | --- | --- |
{per_class_lines}

## Keterbatasan

{limitations_md}

## Penggunaan yang Dimaksud

{intended_use_md}

## Sitasi

> {citation}
{extra_md}

---

*Generated by `forestwatch.outputs.model_card.render_model_card`.*
"""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")
    return out
